### ISSUE TITLE
Missing ro.kuberam.maven:junit-tests:jar:0.1

### ISSUE THREAD

**Issue by aazander** [claudius108/crypto-java-lib#1]
I am attempting to modify the crypto-java-lib but the dependency on ro.kuberam.maven:junit-tests:jar:0.1 cannot be resolved.

**Comment by claudius108** [comment]
Hi,

Thank you for pointing this. I just released the missing dependency to maven central repository.

You have to wait for a while, in order to be published there.

**Comment by aazander** [comment]
Thanks a lot for your promt response.

Andrew Zander



From:  claudius108 <notifications@github.com>
Reply-To:  claudius108/crypto-java-lib
<reply+00b9140603d98a784fa28a98b83a09e6f981695ef1d3440c92cf000000011156f75d9
2a169ce04427574@reply.github.com>
Date:  Tuesday, 28 April 2015 5:23 pm
To:  claudius108/crypto-java-lib <crypto-java-lib@noreply.github.com>
Cc:  Andrew Zander <zander_aa@bigpond.com>
Subject:  Re: [crypto-java-lib] Missing ro.kuberam.maven:junit-tests:jar:0.1
(#1)


Hi,

Thank you for pointing this. I just released the missing dependency to maven
central repository.

You have to wait for a while, in order to be published there.


Reply to this email directly or view it on GitHub
<https://github.com/claudius108/crypto-java-lib/issues/1#issuecomment-969566
15> .

**Comment by joewiz** [comment]
Looks like this issue can be closed?

**Comment by claudius108** [comment]
Yes.
